### ISSUE TITLE
Refactorizar la tabla huesped en el diagrama de casos de uso

### ISSUE THREAD

**Issue by Gavila25** [Raulglezm/proyecto_ets#11]
¿Qué es el huesped? Es un nombre que no es entendible a la hora de verlo desde fuera, si es algo como un invitado yo le pondría ese nombre.
También revisar las faltas de ortografía en los diagramas(almaceness) #4

**Comment by wenhuich** [comment]
Se cierra este issu porque ya esta corregido lo que se pide
